In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"cardio_train.csv")

In [5]:
df

      id;age;gender;height;weight;ap_hi;ap_lo;cholesterol;gluc;smoke;alco;active;cardio
0                  0;18393;2;168;62.0;110;80;1;1;0;0;1;0
1                  1;20228;1;156;85.0;140;90;3;1;0;0;1;1
2                  2;18857;1;165;64.0;130;70;3;1;0;0;0;1
3                 3;17623;2;169;82.0;150;100;1;1;0;0;1;1
4                  4;17474;1;156;56.0;100;60;1;1;0;0;0;0
...                                                  ...
69995          99993;19240;2;168;76.0;120;80;1;1;1;0;1;0
69996         99995;22601;1;158;126.0;140;90;2;2;0;0;1;1
69997         99996;19066;2;183;105.0;180;90;3;1;0;1;0;1
69998          99998;22431;1;163;72.0;135;80;1;2;0;0;0;1
69999          99999;20540;1;170;72.0;120;80;2;1;0;0;1;0

[70000 rows x 1 columns]

In [21]:
df.columns

Index(['id;age;gender;height;weight;ap_hi;ap_lo;cholesterol;gluc;smoke;alco;active;cardio'], dtype='str')

In [23]:
raw_header_string = df.columns.tolist()[0]
raw_header_string

'id;age;gender;height;weight;ap_hi;ap_lo;cholesterol;gluc;smoke;alco;active;cardio'

In [24]:
column_names = raw_header_string.split(';')
column_names

['id',
 'age',
 'gender',
 'height',
 'weight',
 'ap_hi',
 'ap_lo',
 'cholesterol',
 'gluc',
 'smoke',
 'alco',
 'active',
 'cardio']

In [29]:
new_df = df[raw_header_string].str.split(';', expand=True)

In [30]:
new_df.colums = column_names

C:\Users\bhavy\AppData\Local\Temp\ipykernel_20756\2107038095.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  new_df.colums = column_names

In [35]:
df.columns[0]

'id;age;gender;height;weight;ap_hi;ap_lo;cholesterol;gluc;smoke;alco;active;cardio'

In [37]:
df_split = df[df.columns[0]].str.split(';', expand=True)

In [38]:
column_names

['id',
 'age',
 'gender',
 'height',
 'weight',
 'ap_hi',
 'ap_lo',
 'cholesterol',
 'gluc',
 'smoke',
 'alco',
 'active',
 'cardio']

In [39]:
df_split.columns = column_names

In [40]:
df_split.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [41]:
df = df_split

In [42]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [43]:
df.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='str')